# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python downloader.py linux ${{ secrets.ACCESS_TOKEN }}
    - name: Build Linux
      run: |
        python setup.py bdist_wheel
        python rename.py linux_intel
    - name: Build Linux aarch
      run: |
        python setup.py bdist_wheel
        python rename.py linux_aarch
    - name: Publish
      #env:
        #TWINE_USERNAME: ${{ secrets.PYPI_USER_NAME }}
        #TWINE_PASSWORD: ${{ secrets.PYPI_PASS_WORD }}
      run: |
        twine upload dist/*
